#!/bin/zsh
#Really only here so that I might remember where these files actually are supposed to go
files=()
files+='/home/fizzo/.vim/UltiSnips'
files+='/home/fizzo/.vimrc'
files+='/home/fizzo/.zprofile'
files+='/home/fizzo/.zshrc'
files+='/home/fizzo/.config/termite'
files+='/etc/tmux.conf'
files+='/home/fizzo/.mpd/mpd.conf'
files+='/home/fizzo/.ncmpcpp'
files+='/home/fizzo/.xinitrc'
files+='/home/fizzo/.xmonad/xmonad.hs'
files+='/home/fizzo/.xmobarrc'
files+='/home/fizzo/.stalonetrayrc'

if (( $# == 0 ))
then
    for f in $files
    do
        if [[ -h $f ]]
        then
            printf "        $f already a symlink, ignoring\n"
        elif [[ -e $f ]]
        then
            printf "$f exists, move it manually or '$0 move'\n"
        else
            printf "ln -s $PWD/$f:t $f\n"
            ln -s $PWD/$f:t $f
        fi
    done
elif (( $# == 1 )) && [[ $1 == clean ]]
then
    for f in $files
    do
        if [[ -h $f ]]
        then
            printf "rm $f\n"
            rm $f
        elif [[ -e $f ]]
        then
            printf "$f exists, but isn't a symlink, ignored\n"
        fi
    done
elif (( $# == 1 )) && [[ $1 == move ]]
then
    for f in $files
    do
        if [[ -e $f && ! -h $f ]] #Dont move symlink
        then
            printf "mv $f .\n"
            mv $f .
        fi
    done
fi
