* live media
** booted EFI?
ls /sys/firmware/efi/efivars
** have internet?
wifi-menu or nmcli or wpa_cli
** right time?
timedatectl set-ntp true 

* install
** mount
if efi, mount efi on /boot
** base
pacstrap /mnt base base-devel
** fstab
genfstab -U /mnt >> /mnt/etc/fstab

can get uuids in /dev/disk/by-uuid
** chroot
arch-chroot /mnt
alias l="ls --color=always"
** timezone
ln -sf /usr/share/zoneinfo/Europe/Stockholm /etc/localtime
timedatectl set-ntp true 
hwclock --systohc
** locale
vim /etc/locale.gen
want en_US utf8, sv_SE utf8+iso

locale-gen
echo LANG=en_US.UTF-8 > /etc/locale.conf
** host
echo arc > /etc/hostname
** network again
pacman -S wpa_supplicant dialog
wpa_supplicant with wpa_cli is good.

/etc/wpa_supplicant/wpa_supplicant-wlan0.conf:
    ctrl_interface=/var/run/wpa_supplicant
    ctrl_interface_group=/var/run/wpa_supplicant
    update_config=1
    
Then wpa_cli can connect, though check with `interface` if it's a dummy.

Use dhcpcd or networkd to get an ip, the first can be one-shotted
easily for testing, the other won't delay startup at boot-time if
enabled.
** root pw
passwd
** bootloader
*** efibootmgr
pacman -S efibootmgr
efibootmgr -d /dev/sda -p 1 -c -L "arch" -l /vmlinuz-linux -u "root=/dev/sda2 rw initrd=/intel-ucode.img initrd=/initramfs-linux.img"

* reboot
systemctl enable netctl-auto@wlan0

pacman -S tmux git vim fzf htop bash-completion openssh
get dotfiles

** pacaur
curl https://aur.archlinux.org/cgit/aur.git/snapshot/cower.tar.gz > cower.tar.gz
tar xf cower.tar.gz
cd cower
makepkg -si --skippgpcheck
cd ..
cower -d pacaur
cd pacaur
makepkg -si
** abs
pacman -S abs
abs
** user
useradd -m -G wheel fizzo
gpasswd -a fizzo video

visudo -- uncomment wheel
** graphics
pacman -S mesa xorg-server xorg-xinit
    noto-fonts noto-fonts-cjk noto-fonts-emoji dina-font ttf-dejavu
    xmonad xmonad-contrib xmobar trayer
    firefox dmenu maim
    xorg-xrandr xorg-xbacklight feh
    sxiv mpv evince zathura
** audio
pacman -S pulseaudio pavucontrol
** autologin
/etc/systemd/system/getty@tty1.service.d/override.conf
    [Service]
    Type=simple
    ExecStart=
    ExecStart=-/usr/bin/agetty --autologin fizzo --noclear %I $TERM

add the .profile if uncommented
** notifs
pacman -S dunst
** themes
pacman -S gnome-themes-standard lxappearance
** various
*** firefox dirs
.config/user-dirs.dirs
    XDG_DESKTOP_DIR="$HOME/"
*** e-file
pacman -Fo
after
pacman -Fy
